name: feed builder
on:
  workflow_dispatch:
  issues:
    types: opened

env:
  GH_TOKEN: ${{ github.token }}

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Add jq
        run: sudo apt-get update && sudo apt-get install jq -y

      - name: create feed file
        run: |
          gh issue list --state open --limit 250 --json title,body,updatedAt \
          | tee >(jq . > issues.json) \
          | jq --raw-output --from-file genfeed.jq \
          | tee feed.xml

      - name: Commit changes 
        run: |
          git config --global user.email "qmacro-bot@example.com"
          git config --global user.name "qmacro bot"
          git add . 
          git commit -m 'rebuild of feed' || exit 0
          git push
